apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredients
  namespace: pizza
spec:
  selector:
    matchLabels:
      app: ingredients
  replicas: 2
  template:
    metadata:
      labels:
        app: ingredients
    spec:
      containers:
      - name: ingredients
        image: local/ingredients:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        env:
        - name: Jaeger__ServiceName
          value: "ingredients"
        - name: Jaeger__Host
          value: "jaeger-agent"
        - name: Jaeger__Port
          value: "6831"

---

apiVersion: v1
kind: Service
metadata:
  name: ingredients
  namespace: pizza
spec:
  ports:
  - port: 80
  selector:
    app: ingredients
